tasks:
  - init: ./gradlew build

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - editorconfig.editorconfig
    - redhat.java
    - vscjava.vscode-gradle
    - zxh404.vscode-proto3
    - mindaro-dev.file-downloader
    - mike-lischke.vscode-antlr4
    - esbenp.prettier-vscode
    - karlito40.fix-irregular-whitespace
    - viktorzetterstrom.non-breaking-space-highlighter
