pipeline:
  ci:
    image: timbru31/java-node:${JAVA_VERSION}-alpine-jdk-${NODE_VERSION}
    commands:
      - apk update && apk add --no-cache protoc
      - ./gradlew build --info

matrix:
  NODE_VERSION:
    - 16
  JAVA_VERSION:
    - 17