pipeline:
  ci:
    image: timbru31/java-node:${JAVA_VERSION}-alpine-jdk-${NODE_VERSION}
    commands:
      # add the glibc compatibility layer so that we can use the protoc from Maven Central
      - apk update && apk add --no-cache gcompat
      - ./gradlew build --info

matrix:
  NODE_VERSION:
    - 16
  JAVA_VERSION:
    - 17