steps:
  - label: ":gradle: Continuous Integration"
    command: "./.buildkite/ci.sh"
    artifact_paths: "**/build/test-results/*/TEST-*.xml"
    plugins:
      - opencastsoftware/cache#custom-s3-endpoint-fix-s3-sync:
          backend: s3
          compression: tgz
          path: .gradle
          restore: branch
          save: branch
      - opencastsoftware/cache#custom-s3-endpoint-fix-s3-sync:
          backend: s3
          compression: tgz
          path: vscode-plugin/node_modules
          manifest: vscode-plugin/package-lock.json
          restore: file
          save: file
      - docker#v5.8.0:
          image: "timbru31/java-node:17-jdk-16"

  - wait: ~
    continue_on_failure: true

  - label: ":junit: Collect JUnit Results"
    plugins:
      - junit-annotate#v2.4.1:
          artifacts: "**/build/test-results/*/TEST-*.xml"

  - label: ":test-analytics: Test Analytics"
    command: buildkite-agent artifact download "**/build/test-results/*/TEST-*.xml" .
    plugins:
      - test-collector#v1.9.0:
          files: "**/build/test-results/*/TEST-*.xml"
          format: "junit"