steps:
  - label: ":gradle: Continuous Integration"
    command: "./.buildkite/ci.sh"
    artifact_paths: "**/build/test-results/*/TEST-*.xml"
    matrix:
      setup:
        java:
          - "17"
        node:
          - "16"
    plugins:
      - opencastsoftware/cache#ed251b94:
          backend: s3
          path: .gradle
          restore: branch
          save: branch
      - opencastsoftware/cache#ed251b94:
          backend: s3
          manifest: vscode-plugin/package-lock.json
          path: vscode-plugin/node_modules
          restore: file
          save: file
      - docker#v5.7.0:
          image: "timbru31/java-node:{{matrix.java}}-jdk-{{matrix.node}}"
          env:
            - DEBIAN_FRONTEND=noninteractive
            - GRADLE_USER_HOME=/workdir/.gradle

  - wait: ~
    continue_on_failure: true

  - label: ":junit: Collect JUnit Results"
    plugins:
      - junit-annotate#v2.4.1:
          artifacts: "**/build/test-results/*/TEST-*.xml"

  - label: ":test-analytics: Test Analytics"
    command: buildkite-agent artifact download "**/build/test-results/*/TEST-*.xml" .
    plugins:
      - test-collector#v1.8.0:
          files: "**/build/test-results/*/TEST-*.xml"
          format: "junit"