/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mina_lang.gradle;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * A simple unit test for the 'org.mina_lang.gradle.greeting' plugin.
 */
class MinaPluginTest {
    @Test void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("org.mina_lang.gradle");

        // Verify the result
        assertNotNull(project.getPlugins().getAt("org.mina_lang.gradle"));
    }
}
