pipeline:
  renovate:
    image: renovate/renovate:slim@sha256:1e68e9096d869f3717938cda93ab1ce23d648e1b4db161da52326f72c8c48e57
    environment:
      - LOG_LEVEL=debug
      - RENOVATE_AUTODISCOVER=true
      - RENOVATE_AUTODISCOVER_FILTER=mina-lang/*
      - RENOVATE_ENDPOINT=https://codeberg.org/api/v1/
      - RENOVATE_GIT_AUTHOR=Mina Bot <mina-bot@mina-lang.org>
      - RENOVATE_PLATFORM=gitea
    secrets: [ renovate_token, renovate_git_private_key ]
    when:
      event: cron
      cron: renovate
    commands:
      - renovate

skip_clone: true