name: Continuous Integration

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
    tags: [v*]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [17]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Protobuf Compiler
        uses: arduino/setup-protoc@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Build Common Module
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: compiler/common
          arguments: build

      - name: Publish Common Module
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: compiler/common
          arguments: publish

      - name: Build Syntax Module
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: compiler/syntax
          arguments: build

      - name: Publish Syntax Module
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: compiler/syntax
          arguments: publish

      - name: Build Parser Module
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: compiler/parser
          arguments: build

      - name: Publish Parser Module
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: compiler/parser
          arguments: publish

      - name: Build Intermediate Language Module
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: compiler/intermediate
          arguments: build

      - name: Publish Intermediate Language Module
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: compiler/intermediate
          arguments: publish

      - name: Build JVM Codegen Module
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: compiler/jvm
          arguments: build

      - name: Publish JVM Codegen Module
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: compiler/jvm
          arguments: publish

      - name: Build Language Server
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: lang-server
          arguments: build

      - name: Publish Language Server
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: lang-server
          arguments: publish

      - name: Build VS Code Extension
        if: runner.os == 'Linux'
        working-directory: vscode-plugin
        run: npm install && xvfb-run -a npm run test --silent

      - name: Build VS Code Extension
        if: runner.os != 'Linux'
        working-directory: vscode-plugin
        run: npm install && npm run test --silent
