name: Update Dependency Graph

on:
  push:
    branches:
      - main

jobs:
  update-dependencies:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
        
      - name: Submit Gradle Dependencies
        uses: mikepenz/gradle-dependency-submission@v0.0.4
        with:
          gradle-dependency-path: "gradle-plugin/build.gradle;compiler/common/build.gradle;compiler/syntax/build.gradle;compiler/parser/build.gradle;compiler/intermediate/build.gradle;compiler/jvm/build.gradle;lang-server/build.gradle"
          gradle-build-module: ":gradle-plugin;:compiler:common;:compiler:syntax;:compiler:parser;:compiler:intermediate;:compiler:jvm;:language-server"
